_system/controllers/IdebController.php
<?php
/**
* @link http://www.diecoding.com/
* @author Die Coding (Sugeng Sulistiyawan) <diecoding@gmail.com>
* @copyright Copyright (c) 2018
*/


namespace app\controllers;

use Yii;
use app\models\RecIdeb;
use app\models\searchs\RecIdeb as Admin;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\helpers\Html;
use yii\filters\AccessControl;
use kartik\mpdf\Pdf;

/**
* IdebController implements the CRUD actions for RecIdeb model.
*/
class IdebController extends Controller
{
  /**
  * @inheritdoc
  */
  public function behaviors()
  {
    return [
      'access' => [
        'class' => AccessControl::className(),
        'rules' => [
          [
            'allow' => true,
            'roles' => ['@'],
          ],
        ],
      ],
      'verbs' => [
        'class'   => VerbFilter::className(),
        'actions' => [
          'delete'      => ['post'],
          'bulk-delete' => ['post'],
          // 'update'      => ['post'],
        ],
      ],
    ];
  }

  /**
  * Lists all RecIdeb models.
  *
  * @return mixed
  */
  public function actionIndex($action = 'perseorangan')
  {
    $searchModel  = new Admin();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams, true, strtoupper($action));

    return $this->render(
      'index',
      [
        'searchModel'  => $searchModel,
        'dataProvider' => $dataProvider,
        'action' => strtoupper(str_replace("-", " ", $action)),
      ]
    );
  }


  /**
  * Displays a single RecIdeb model.
  *
  * @param  integer $id
  * @return mixed
  */
  public function actionView($id)
  {
    $request = Yii::$app->request;

    if ($request->isAjax) {
      Yii::$app->response->format = Response::FORMAT_JSON;
      return [
        'title'   => "RecIdeb #{$id}",
        'content' => $this->renderAjax(
          'view',
          [
            'model' => $this->findModel($id),
          ]
        ),
        'footer'  => '<div class="col-xs-12">'.
        Html::button(
          Yii::t('app', 'Tutup'),
          [
            'class'        => 'btn btn-default',
            'data-dismiss' => 'modal',
          ]
          ) .
          Html::a(
            Yii::t('app', 'Proses'),
            ['update', 'id' => $id],
            [
              'class' => 'btn btn-primary',
              // 'role'  => 'modal-remote',
            ]
            ) .
            '</div>'
          ];
        }

        return $this->render(
          'view',
          [
            'model' => $this->findModel($id),
          ]
        );
      }

      /**
      * Updates an existing RecIdeb model.
      * For ajax request will return json object
      * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
      *
      * @param  integer $id
      * @return mixed
      */
      public function actionUpdate($id)
      {
        $model            = $this->findModel($id);
        $action = $model->jenis;
        $model->is_proses = 1;


        if ($model->save(false)) {
          $content = $this->renderPartial(
            'update-'.strtolower($action),
            [
              'model' => $model,
            ]
          );

          $pdf = new Pdf(
            [
              'mode' => Pdf::MODE_CORE,
              'format' => 'Folio',
              'orientation' => 'P',
              'destination' => Pdf::DEST_BROWSER,
              'defaultFont' => '"Times New Roman", serif',
              'defaultFontSize' => '10pt',
              'content' => $content,
              'cssFile' => '@webroot/css/print/proses.min.css',
              'cssInline' => "",
              'options' => [
                'title' => 'BERKAS ' . strtoupper($model->nama) . " " . time(),
                'subject' => 'BERKAS ' . strtoupper($model->nama) . " " . time(),
              ],
              'methods' => [
                // 'SetHeader' => ['No. Antrian: '],
                // 'SetFooter' => ['{PAGENO}']
              ],
              'filename' => 'BERKAS ' . strtoupper($model->nama) . " " . time() . '.pdf',
              'marginLeft' => 20,
              'marginRight' => 20,
              'marginTop' => 10,
              'marginBottom' => 10,
              'marginHeader' => 0,
              'marginFooter' => 0,
            ]
          );

          $response = Yii::$app->response;
          $response->format = Response::FORMAT_RAW;
          $headers = Yii::$app->response->headers;
          $headers->add('Content-Type', 'application/pdf');

          return $pdf->render();
        }

        return $this->goBack();
      }

      /**
      * Delete an existing RecIdeb model.
      * For ajax request will return json object
      * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
      *
      * @param  integer $id
      * @return mixed
      */
      public function actionDelete($id)
      {
        $request = Yii::$app->request;
        $model   = $this->findModel($id);
        $model->is_proses = 2;

        if (!$model->save(false)) {
          Yii::$app->session->setFlash('success', Yii::t('app', 'Data gagal dihapus'));
          return $this->redirect(['index']);
        }

        if ($request->isAjax) {

          /**
          *  Process for ajax request
          */
          Yii::$app->response->format = Response::FORMAT_JSON;
          return [
            'forceReload' => '#crud-datatable-pjax',
            'forceClose'  => true,
          ];
        }

        /**
        *   Process for non-ajax request
        */
        return $this->redirect(['index']);
      }

      /**
      * Delete multiple existing RecIdeb model.
      * For ajax request will return json object
      * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
      *
      * @param  integer $id
      * @return mixed
      */
      public function actionBulkDelete()
      {
        $request = Yii::$app->request;
        $pks     = explode(',', $request->post('pks')); // Array or selected records primary keys

        foreach ($pks as $pk) {
          $model = $this->findModel($pk);
          $model->is_proses = 2;
          $model->save(false);
          // $model->delete();
        }

        if (!empty($pks)) {
          // Yii::$app->session->setFlash('success', count($pks) . ' ' . Yii::t('app', 'Data berhasil dihapus'));
        }

        if ($request->isAjax) {

          /**
          *  Process for ajax request
          */
          Yii::$app->response->format = Response::FORMAT_JSON;
          return [
            'forceReload' => '#crud-datatable-pjax',
            'forceClose'  => true,
          ];
        }

        /**
        *   Process for non-ajax request
        */
        return $this->redirect(['index']);
      }

      /**
      * Finds the RecIdeb model based on its primary key value.
      * If the model is not found, a 404 HTTP exception will be thrown.
      *
      * @param  integer $id
      * @return RecIdeb the loaded model
      * @throws NotFoundHttpException if the model cannot be found
      */
      protected function findModel($id)
      {
        if (($model = RecIdeb::findOne($id)) !== null) {
          return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
      }
    }

_system/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

use app\models\RecIdeb;
use app\models\searchs\RecIdeb as RecIdebSearch;
use app\models\RecLaporan;
use app\models\searchs\RecLaporan as RecLaporanSearch;
use app\models\Posts;

use yii\web\NotFoundHttpException;
use yii\helpers\Html;

class SiteController extends Controller
{
  /**
  * {@inheritdoc}
  */
  public function behaviors()
  {
    return [
      'access' => [
        'class' => AccessControl::className(),
        'only' => ['logout', 'index-secure'],
        'rules' => [
          [
            'actions' => ['logout', 'index-secure'],
            'allow' => true,
            'roles' => ['@'],
          ],
        ],
      ],
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'logout' => ['post'],
        ],
      ],
    ];
  }

  /**
  * {@inheritdoc}
  */
  public function actions()
  {
    return [
      'error' => [
        'class' => 'yii\web\ErrorAction',
      ],
      'captcha' => [
        'class' => 'yii\captcha\CaptchaAction',
        'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
      ],
    ];
  }

  /*
   * Lists all RecLaporan models.
   * @return mixed
   */
  public function actionIndex()
  {
    $searchModel  = new RecLaporanSearch();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
    $dataProvider->pagination->pageSize = 3;

    return $this->render('index', [
      'searchModel'  => $searchModel,
      'dataProvider' => $dataProvider,
    ]);
  }

  /*
   * Displays a single RecLaporan model.
   * @param integer $id
   * @return mixed
   */
  public function actionView($id)
  {
    $request = Yii::$app->request;

    if ($request->isAjax) {
      Yii::$app->response->format = Response::FORMAT_JSON;
      return [
        'title'   => "RecLaporan #{$id}",
        'content' => $this->renderAjax('view', [
          'model' => $this->findModel($id),
        ]),
        'footer'  => '<div class="col-xs-12">'.
          Html::button(Yii::t('app', 'Tutup'), [
            'class'        => 'btn btn-default',
            'data-dismiss' => 'modal',
          ]
          ) .
        '</div>'
      ];
    }

    return $this->goHome();
  }

  /**
  * Displays homepage.
  *
  * @return string
  */
  public function actionIndexSecure()
  {
    $searchModel                        = new RecIdebSearch();
    $dataProvider                       = $searchModel->search(Yii::$app->request->queryParams);
    $dataProvider->pagination->pageSize = 10;

    return $this->render('index-secure', [
      'searchModel' => $searchModel,
      'dataProvider' => $dataProvider,
    ]);
  }


  /**
  * Creates a new RecIdeb model.
  * For ajax request will return json object
  * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
  * @return mixed
  */
  public function actionCreate($action = 'perseorangan')
  {
    $request = Yii::$app->request;
    $model   = new RecIdeb();

    if ($request->isAjax) {

      /*
      *  Process for ajax request
      */
      Yii::$app->response->format = Response::FORMAT_JSON;
      if ($request->isGet) {
        return [
          'title'   => Yii::t('app', 'Formulir Permohonan IDEB ' . strtoupper(str_replace("-", " ", $action))),
          'content' => $this->renderAjax('create-' . strtolower($action), [
            'model' => $model,
          ]),
          'footer'  => '<div class="col-md-12">'.
          Html::button(Yii::t('app', 'Tutup'), [
            'class'        => 'btn btn-default',
            'data-dismiss' => 'modal',
          ]
          ) .
          Html::button(Yii::t('app', 'Simpan'), [
            'class' => 'btn btn-primary',
            'type'  => 'submit',
          ]
          ) .
          '</div>'
        ];
      }

      if ($model->load($request->post())) {

        if (($data = $model->setCreate(strtoupper($action))) && $model->save()) {
          return [
            'forceReload' => '#crud-datatable-pjax',
            'title'       => Yii::t('app', 'Formulir Permohonan IDEB ' . strtoupper(str_replace("-", " ", $action))),
            'content'     => '<span class="text-success">'.Yii::t('app', 'Data berhasil disimpan').'</span>',
            'footer'      => '<div class="col-md-12">'.
            Html::button(Yii::t('app', 'Tutup'), [
              'class'        => 'btn btn-default',
              'data-dismiss' => 'modal',
            ]
            ) .
            Html::a(Yii::t('app', 'Isi Formulir Lagi'),
            ['create', 'action' => $action],
            [
              'class' => 'btn btn-primary',
              'role'  => 'modal-remote',
            ]
            ) .
            '</div>'
          ];
        } else {
          return [
            'title'   => Yii::t('app', 'Formulir Permohonan IDEB ' . strtoupper(str_replace("-", " ", $action))),
            'content' => $this->renderAjax('create-' . strtolower($action), [
              'model' => $model,
            ]),
            'footer'  => '<div class="col-md-12">'.
            Html::button(Yii::t('app', 'Tutup'), [
              'class'        => 'btn btn-default',
              'data-dismiss' => 'modal',
            ]
            ) .
            Html::button(Yii::t('app', 'Simpan'), [
              'class' => 'btn btn-primary',
              'type'  => 'submit',
            ]
            ) .
            '</div>'

          ];
        }
      }
    }

    /*
     *  Process for non-ajax request
     */
    if ($model->load($request->post())) {

      // echo "<pre>";print_r($model->setCreate());exit;

      if (($data = $model->setCreate(strtoupper($action))) && $model->save()) {
        Yii::$app->session->setFlash('success', Yii::t('app', 'Data berhasil disimpan'));
      }
    }

    return $this->render('create-' . strtolower($action), [
      'model' => $model,
    ]);
  }

  /**
  * Login action.
  *
  * @return Response|string
  */
  public function actionLogin()
  {
    if (!Yii::$app->user->isGuest) {
      return $this->goHome();
    }

    $model = new LoginForm();
    if ($model->load(Yii::$app->request->post()) && $model->login()) {
      return $this->goBack();
    }

    $model->password = '';
    return $this->render('login', [
      'model' => $model,
    ]);
  }

  /**
  * Logout action.
  *
  * @return Response
  */
  public function actionLogout()
  {
    Yii::$app->user->logout();

    return $this->goHome();
  }

  /**
  * Displays contact page.
  *
  * @return Response|string
  */
  // public function actionContact()
  // {
  //   $model = new ContactForm();
  //   if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
  //     Yii::$app->session->setFlash('contactFormSubmitted');
  //
  //     return $this->refresh();
  //   }
  //   return $this->render('contact', [
  //     'model' => $model,
  //   ]);
  // }

  /**
  * Displays panduan page.
  *
  * @return string
  */
  public function actionPanduan()
  {
    $model = Posts::findOne(1);

    return $this->render('panduan', [
      'model' => $model
    ]);
  }


  /*
   * Finds the RecLaporan model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param integer $id
   * @return RecLaporan the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id)
  {

    if (($model = RecLaporan::findOne($id)) !== null) {
      return $model;
    }

    throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
  }
}

_system/views/ideb/_columns-badan-usaha.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

return [
  // [
  //   'class' => 'kartik\grid\CheckboxColumn',
  //   'width' => '20px',
  // ],
  [
    'class' => 'kartik\grid\SerialColumn',
    'width' => '30px',
  ],
  // [
    // 'class'     => '\kartik\grid\DataColumn',
    // 'attribute' => 'id',
  // ],
  [
    'class'     => '\kartik\grid\DataColumn',
    'attribute' => 'nomor_identitas',
  ],
  [
    'class'     => '\kartik\grid\DataColumn',
    'attribute' => 'nama',
  ],
  [
    'class'     => '\kartik\grid\DataColumn',
    'attribute' => 'nama_bu',
  ],
  [
    'class'     => '\kartik\grid\DataColumn',
    'attribute' => 'npwp',
  ],
  [
    'class'     => '\kartik\grid\DataColumn',
    'attribute' => 'no_telepon',
  ],
  [
    'class'     => '\kartik\grid\DataColumn',
    'attribute' => 'nomor_akta_pendirian',
  ],
  [
    'class'     => '\kartik\grid\DataColumn',
    'attribute' => 'nomor_anggaran_dasar',
  ],
  // [
    // 'class'     => '\kartik\grid\DataColumn',
    // 'attribute' => 'alamat_sesuai_kartu',
  // ],
  // [
    // 'class'     => '\kartik\grid\DataColumn',
    // 'attribute' => 'alamat_lain',
  // ],
  // [
    // 'class'     => '\kartik\grid\DataColumn',
    // 'attribute' => 'alasan_pengajuan',
  // ],
  // [
    // 'class'     => '\kartik\grid\DataColumn',
    // 'attribute' => 'created_at',
  // ],
  // [
    // 'class'     => '\kartik\grid\DataColumn',
    // 'attribute' => 'updated_at',
  // ],

  [
      'class'     => '\kartik\grid\DataColumn',
      'attribute' => 'is_proses',
      'label'     => 'Status',
      'format'    => 'raw',
      'value' => function ($model) {
          return $model->formatIsProses($model->is_proses);
      }
  ],
  [
    'class'      => 'kartik\grid\ActionColumn',
    'options' => [
      'style' => 'min-width: 100px',
    ],
    'template'   => '{view} {proses} {delete}',
    'dropdown'   => false,
    'vAlign'     => 'middle',
    'urlCreator' => function ($action, $model, $key, $index) {
        $url = Url::to([$action, 'id' => $key]);
        return $url;
    },

    'buttons' => [
      'view'   => function ($url, $model) {
          return Html::a('<i class="fa fa-eye"></i>', $url, [
          'data-original-title' => Yii::t('app', 'Lihat'),
          'title'               => Yii::t('app', 'Lihat'),
          'data-toggle'         => 'tooltip',
          'class'               => 'btn btn-primary btn-xs',
          'role'                => 'modal-remote',
        ]);
      },
      'proses' => function ($url, $model) {
          return Html::a('<i class="fa fa-print"></i>', ['update', 'id' => $model->id], [
          'data-original-title' => Yii::t('app', 'Proses'),
          'title'               => Yii::t('app', 'Proses'),
          'data-toggle'         => 'tooltip',
          'class'               => 'btn btn-warning btn-xs',
          'target'              => '_blank',
          'data-method'         => 'post',
        ]);
      },
      'delete' => function ($url, $model) {
          return Html::a('<i class="fa fa-trash"></i>', $url, [
          'data-original-title'  => Yii::t('app', 'Hapus'),
          'title'                => Yii::t('app', 'Hapus'),
          'data-toggle'          => 'tooltip',
          'class'                => 'btn btn-danger btn-xs',
          'role'                 => 'modal-remote',
          'data-confirm'         => false,
          'data-method'          => false, // for overide yii data api
          'data-request-method'  => 'post',
          'data-confirm-title'   => Yii::t('app', 'Are you sure?'),
          'data-confirm-message' => Yii::t('app', 'Are you sure want to delete this item'),
        ]);
      }
    ],

    'contentOptions' => [
      'class' => 'td-actions skip-export kv-align-center kv-align-middle',
    ],
  ],

];

_system/views/ideb/_columns-perseorangan.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

return [
  // [
  //   'class' => 'kartik\grid\CheckboxColumn',
  //   'width' => '20px',
  // ],
  [
    'class' => 'kartik\grid\SerialColumn',
    'width' => '30px',
  ],
  // [
    // 'class'     => '\kartik\grid\DataColumn',
    // 'attribute' => 'id',
  // ],
  [
    'class'     => '\kartik\grid\DataColumn',
    'attribute' => 'nomor_identitas',
  ],
  [
    'class'     => '\kartik\grid\DataColumn',
    'attribute' => 'nama',
  ],
  [
    'class'     => '\kartik\grid\DataColumn',
    'attribute' => 'tempat_lahir',
  ],
  [
    'class'     => '\kartik\grid\DataColumn',
    'attribute' => 'tanggal_lahir',
    'format'    => ['date', 'php:d F Y'],
  ],
  [
    'class'     => '\kartik\grid\DataColumn',
    'attribute' => 'jenis_kelamin',
    'label'     => 'JK',
    'value'     => function ($model) {
        return substr($model->jenis_kelamin, 0, 1);
    }
  ],
  [
    'class'     => '\kartik\grid\DataColumn',
    'attribute' => 'no_telepon',
  ],
  [
    'class'     => '\kartik\grid\DataColumn',
    'attribute' => 'nama_ibu_debitur',
  ],
  // [
    // 'class'     => '\kartik\grid\DataColumn',
    // 'attribute' => 'alamat_sesuai_kartu',
  // ],
  // [
    // 'class'     => '\kartik\grid\DataColumn',
    // 'attribute' => 'alamat_lain',
  // ],
  // [
    // 'class'     => '\kartik\grid\DataColumn',
    // 'attribute' => 'alasan_pengajuan',
  // ],
  // [
    // 'class'     => '\kartik\grid\DataColumn',
    // 'attribute' => 'created_at',
  // ],
  // [
    // 'class'     => '\kartik\grid\DataColumn',
    // 'attribute' => 'updated_at',
  // ],

  [
      'class'     => '\kartik\grid\DataColumn',
      'attribute' => 'is_proses',
      'label'     => 'Status',
      'format'    => 'raw',
      'value' => function ($model) {
          return $model->formatIsProses($model->is_proses);
      }
  ],
  [
    'class'      => 'kartik\grid\ActionColumn',
    'options' => [
      'style' => 'min-width: 100px',
    ],
    'template'   => '{view} {proses} {delete}',
    'dropdown'   => false,
    'vAlign'     => 'middle',
    'urlCreator' => function ($action, $model, $key, $index) {
        $url = Url::to([$action, 'id' => $key]);
        return $url;
    },

    'buttons' => [
      'view'   => function ($url, $model) {
          return Html::a('<i class="fa fa-eye"></i>', $url, [
          'data-original-title' => Yii::t('app', 'Lihat'),
          'title'               => Yii::t('app', 'Lihat'),
          'data-toggle'         => 'tooltip',
          'class'               => 'btn btn-primary btn-xs',
          'role'                => 'modal-remote',
        ]);
      },
      'proses' => function ($url, $model) {
          return Html::a('<i class="fa fa-print"></i>', ['update', 'id' => $model->id], [
          'data-original-title' => Yii::t('app', 'Proses'),
          'title'               => Yii::t('app', 'Proses'),
          'data-toggle'         => 'tooltip',
          'class'               => 'btn btn-warning btn-xs',
          'target'              => '_blank',
          'data-method'         => 'post',
        ]);
      },
      'delete' => function ($url, $model) {
          return Html::a('<i class="fa fa-trash"></i>', $url, [
          'data-original-title'  => Yii::t('app', 'Hapus'),
          'title'                => Yii::t('app', 'Hapus'),
          'data-toggle'          => 'tooltip',
          'class'                => 'btn btn-danger btn-xs',
          'role'                 => 'modal-remote',
          'data-confirm'         => false,
          'data-method'          => false, // for overide yii data api
          'data-request-method'  => 'post',
          'data-confirm-title'   => Yii::t('app', 'Are you sure?'),
          'data-confirm-message' => Yii::t('app', 'Are you sure want to delete this item'),
        ]);
      }
    ],

    'contentOptions' => [
      'class' => 'td-actions skip-export kv-align-center kv-align-middle',
    ],
  ],

];

_system/views/ideb/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\master\RecIdebPerorangan */
/* @var $form yii\widgets\ActiveForm */
?>


<?php $form = ActiveForm::begin(); ?>

<?= $form->field($model, 'nomor_identitas')->textInput(['maxlength' => true]) ?>

<?= $form->field($model, 'nama')->textInput(['maxlength' => true]) ?>

<?= $form->field($model, 'tempat_lahir')->textInput(['maxlength' => true]) ?>

<?= $form->field($model, 'tanggal_lahir')->textInput() ?>

<?= $form->field($model, 'jenis_kelamin')->dropDownList([ 'Laki-laki' => 'Laki-laki', 'Perempuan' => 'Perempuan', '' => '', ], ['prompt' => '']) ?>

<?= $form->field($model, 'no_telepon')->textInput(['maxlength' => true]) ?>

<?= $form->field($model, 'nama_ibu_debitur')->textInput(['maxlength' => true]) ?>

<?= $form->field($model, 'alamat_sesuai_kartu')->textarea(['rows' => 6]) ?>

<?= $form->field($model, 'alamat_lain')->textarea(['rows' => 6]) ?>

<?= $form->field($model, 'alasan_pengajuan')->textarea(['rows' => 6]) ?>

<?= $form->field($model, 'created_at')->textInput() ?>

<?= $form->field($model, 'updated_at')->textInput() ?>

<?= $form->field($model, 'is_proses')->textInput() ?>

<?php if (!Yii::$app->request->isAjax){ ?>
  <div class="form-group">
    <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Simpan') : Yii::t('app', 'Perbarui'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
  </div>
<?php } ?>

<?php ActiveForm::end(); ?>

_system/views/ideb/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\master\RecIdebPerorangan */

?>

<?= $this->render('_form', [
  'model' => $model,
]) ?>

_system/views/ideb/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset;
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\searchs\Admin */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'IDEB ' . $action);
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>

<div id="ajaxCrudDatatable">
  <?=  GridView::widget([
    'id'           => 'crud-datatable',
    'dataProvider' => $dataProvider,
    // 'filterModel'  => $searchModel,
    'pjax'         => true,
    'columns'      => require(__DIR__.'/_columns-'. str_replace(" ", "-", strtolower($action)) .'.php'),
    'toolbar'      => [
      [
        'content' => Html::a('<i class="fa fa-plus"></i>', ['/site/create', 'action' => str_replace(" ", "-", strtolower($action))], ['role' => 'modal-remote', 'title' => Yii::t('app', 'Tambah Data'), 'class'=>'btn btn-default']) .
        Html::a('<i class="fa fa-repeat"></i>', [''], ['data-pjax' => 1, 'class' => 'btn btn-default', 'title' => Yii::t('app', 'Reset Grid')]) .
        '{toggleData}' .
        '{export}',
      ],
    ],
    'exportConfig' => [
      GridView::PDF   => [
        'filename'         => str_replace(" ", "_", str_replace(" / ", " ", $this->title)).date('_dmYHis'),
        'showConfirmAlert' => false,
        'target'           => '_self',
        'deleteAfterSave'  => true,
      ],
      GridView::EXCEL => [
        'filename'         => str_replace(" ", "_", str_replace(" / ", " ", $this->title)).date('_dmYHis'),
        'showConfirmAlert' => false,
        'target'           => '_self',
        'deleteAfterSave'  => true,
      ],
    ],
    'striped'        => true,
    'condensed'      => true,
    'responsive'     => true,
    'responsiveWrap' => false,
    'panel' => [
      'type'       => 'default',
      'heading'    => $this->title,
      // 'before'  => '<em>'.Yii::t('app', '* Resize table columns just like a spreadsheet by dragging the column edges.').'</em>',
      'after'      => false,
    ]
  ]
  ) ?>

</div>

<?php

Modal::begin([
  "id"     => "ajaxCrudModal",
  "size"   => "modal-lg",
  "footer" => "", // always need it for jquery plugin
]);

Modal::end();

?>