_system/controllers/PostController.php
<?php
/**
 * @link http://www.diecoding.com/
 * @author Die Coding (Sugeng Sulistiyawan) <diecoding@gmail.com>
 * @copyright Copyright (c) 2018
 */


namespace app\controllers;

use Yii;
use app\models\Posts;
use app\models\searchs\Posts as PostsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use app\models\form\UploadSlider;

use yii\helpers\FileHelper;

/**
 *
 * PostController implements the CRUD actions for Posts model.
 */
class PostController extends Controller
{

    /**
     *
     *
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
        'access' => [
        'class' => AccessControl::className(),
        'rules' => [
          [
            'actions' => ['update', 'slider'],
            'allow'   => true,
            'roles'   => ['@'],
          ],
        ],
        ],
        'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'delete' => ['POST'],
        ],
        ],
        ];
    }

    /**
     *
     * Lists all Posts models.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render(
            'index',
            [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            ]
        );
    }

    /**
     *
     * Displays a single Posts model.
     *
     * @param  integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render(
            'view',
            [
            'model' => $this->findModel($id),
            ]
        );
    }

    /**
     *
     * Creates a new Posts model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Posts();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render(
                'create',
                [
                'model' => $model,
                ]
            );
        }
    }

    /**
     *
     * Updates an existing Posts model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param  integer $id
     * @return mixed
     */
    public function actionUpdate($id, $ajax = 0, $redirect = null)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if ($redirect) {
                return $this->redirect([$redirect]);
            } else {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            if ($ajax == 1) {
                return $this->renderAjax(
                    'update',
                    [
                    'model' => $model,
                    ]
                );
            } else {
                return $this->render(
                    'update',
                    [
                    'model' => $model,
                    ]
                );
            }
        }
    }

    /**
     *
     * Deletes an existing Posts model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param  integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionSlider($action)
    {
        if ($action === 'unggah') {
            $model = new UploadSlider();

            if ($model->load(Yii::$app->request->post())) {
                $model->imageFile = UploadedFile::getInstance($model, 'imageFile');

                if ($model->upload()) {
                    Yii::$app->session->setFlash('success', 'File berhasil diunggah.');
                } else {
                    Yii::$app->session->setFlash('error', 'Gagal mengunggah file.');
                }

                return $this->goHome();
            }

            return $this->renderAjax('slider-unggah', ['model' => $model]);
        } elseif ($action === 'hapus') {
            if (isset($_POST['image'])) {
                $img = $_POST['image'];
                $dir    = Yii::getAlias('@webroot/images/galery') . '/';

                //delete old images
                $oldImages = FileHelper::findFiles($dir, [
        'only' => [
          $img,
        ],
      ]);
                foreach ($oldImages as $i) {
                    @unlink($i);
                }

                Yii::$app->session->setFlash('success', 'File berhasil dihapus.');
                return $this->goHome();
            }

            return $this->renderAjax('slider-hapus');
        }

        return $this->goHome();
    }

    /**
     *
     * Finds the Posts model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param  integer $id
     * @return Posts the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Posts::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

_system/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

use app\models\RecIdeb;
use app\models\searchs\RecIdeb as RecIdebSearch;
use app\models\RecLaporan;
use app\models\searchs\RecLaporan as RecLaporanSearch;
use app\models\Posts;

use yii\web\NotFoundHttpException;
use yii\helpers\Html;

class SiteController extends Controller
{
  /**
  * {@inheritdoc}
  */
  public function behaviors()
  {
    return [
      'access' => [
        'class' => AccessControl::className(),
        'only' => ['logout', 'index-secure'],
        'rules' => [
          [
            'actions' => ['logout', 'index-secure'],
            'allow' => true,
            'roles' => ['@'],
          ],
        ],
      ],
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'logout' => ['post'],
        ],
      ],
    ];
  }

  /**
  * {@inheritdoc}
  */
  public function actions()
  {
    return [
      'error' => [
        'class' => 'yii\web\ErrorAction',
      ],
      'captcha' => [
        'class' => 'yii\captcha\CaptchaAction',
        'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
      ],
    ];
  }

  /*
   * Lists all RecLaporan models.
   * @return mixed
   */
  public function actionIndex()
  {
    $searchModel  = new RecLaporanSearch();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
    $dataProvider->pagination->pageSize = 3;

    return $this->render('index', [
      'searchModel'  => $searchModel,
      'dataProvider' => $dataProvider,
    ]);
  }

  /*
   * Displays a single RecLaporan model.
   * @param integer $id
   * @return mixed
   */
  public function actionView($id)
  {
    $request = Yii::$app->request;

    if ($request->isAjax) {
      Yii::$app->response->format = Response::FORMAT_JSON;
      return [
        'title'   => "RecLaporan #{$id}",
        'content' => $this->renderAjax('view', [
          'model' => $this->findModel($id),
        ]),
        'footer'  => '<div class="col-xs-12">'.
          Html::button(Yii::t('app', 'Tutup'), [
            'class'        => 'btn btn-default',
            'data-dismiss' => 'modal',
          ]
          ) .
        '</div>'
      ];
    }

    return $this->goHome();
  }

  /**
  * Displays homepage.
  *
  * @return string
  */
  public function actionIndexSecure()
  {
    $searchModel                        = new RecIdebSearch();
    $dataProvider                       = $searchModel->search(Yii::$app->request->queryParams);
    $dataProvider->pagination->pageSize = 10;

    return $this->render('index-secure', [
      'searchModel' => $searchModel,
      'dataProvider' => $dataProvider,
    ]);
  }


  /**
  * Creates a new RecIdeb model.
  * For ajax request will return json object
  * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
  * @return mixed
  */
  public function actionCreate($action = 'perseorangan')
  {
    $request = Yii::$app->request;
    $model   = new RecIdeb();

    if ($request->isAjax) {

      /*
      *  Process for ajax request
      */
      Yii::$app->response->format = Response::FORMAT_JSON;
      if ($request->isGet) {
        return [
          'title'   => Yii::t('app', 'Formulir Permohonan IDEB ' . strtoupper(str_replace("-", " ", $action))),
          'content' => $this->renderAjax('create-' . strtolower($action), [
            'model' => $model,
          ]),
          'footer'  => '<div class="col-md-12">'.
          Html::button(Yii::t('app', 'Tutup'), [
            'class'        => 'btn btn-default',
            'data-dismiss' => 'modal',
          ]
          ) .
          Html::button(Yii::t('app', 'Simpan'), [
            'class' => 'btn btn-primary',
            'type'  => 'submit',
          ]
          ) .
          '</div>'
        ];
      }

      if ($model->load($request->post())) {

        if (($data = $model->setCreate(strtoupper($action))) && $model->save()) {
          return [
            'forceReload' => '#crud-datatable-pjax',
            'title'       => Yii::t('app', 'Formulir Permohonan IDEB ' . strtoupper(str_replace("-", " ", $action))),
            'content'     => '<span class="text-success">'.Yii::t('app', 'Data berhasil disimpan').'</span>',
            'footer'      => '<div class="col-md-12">'.
            Html::button(Yii::t('app', 'Tutup'), [
              'class'        => 'btn btn-default',
              'data-dismiss' => 'modal',
            ]
            ) .
            Html::a(Yii::t('app', 'Isi Formulir Lagi'),
            ['create', 'action' => $action],
            [
              'class' => 'btn btn-primary',
              'role'  => 'modal-remote',
            ]
            ) .
            '</div>'
          ];
        } else {
          return [
            'title'   => Yii::t('app', 'Formulir Permohonan IDEB ' . strtoupper(str_replace("-", " ", $action))),
            'content' => $this->renderAjax('create-' . strtolower($action), [
              'model' => $model,
            ]),
            'footer'  => '<div class="col-md-12">'.
            Html::button(Yii::t('app', 'Tutup'), [
              'class'        => 'btn btn-default',
              'data-dismiss' => 'modal',
            ]
            ) .
            Html::button(Yii::t('app', 'Simpan'), [
              'class' => 'btn btn-primary',
              'type'  => 'submit',
            ]
            ) .
            '</div>'

          ];
        }
      }
    }

    /*
     *  Process for non-ajax request
     */
    if ($model->load($request->post())) {

      // echo "<pre>";print_r($model->setCreate());exit;

      if (($data = $model->setCreate(strtoupper($action))) && $model->save()) {
        Yii::$app->session->setFlash('success', Yii::t('app', 'Data berhasil disimpan'));
      }
    }

    return $this->render('create-' . strtolower($action), [
      'model' => $model,
    ]);
  }

  /**
  * Login action.
  *
  * @return Response|string
  */
  public function actionLogin()
  {
    if (!Yii::$app->user->isGuest) {
      return $this->goHome();
    }

    $model = new LoginForm();
    if ($model->load(Yii::$app->request->post()) && $model->login()) {
      return $this->goBack();
    }

    $model->password = '';
    return $this->render('login', [
      'model' => $model,
    ]);
  }

  /**
  * Logout action.
  *
  * @return Response
  */
  public function actionLogout()
  {
    Yii::$app->user->logout();

    return $this->goHome();
  }

  /**
  * Displays contact page.
  *
  * @return Response|string
  */
  // public function actionContact()
  // {
  //   $model = new ContactForm();
  //   if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
  //     Yii::$app->session->setFlash('contactFormSubmitted');
  //
  //     return $this->refresh();
  //   }
  //   return $this->render('contact', [
  //     'model' => $model,
  //   ]);
  // }

  /**
  * Displays panduan page.
  *
  * @return string
  */
  public function actionPanduan()
  {
    $model = Posts::findOne(1);

    return $this->render('panduan', [
      'model' => $model
    ]);
  }


  /*
   * Finds the RecLaporan model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param integer $id
   * @return RecLaporan the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id)
  {

    if (($model = RecLaporan::findOne($id)) !== null) {
      return $model;
    }

    throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
  }
}

_system/views/site/_columns-secure.php
<?php
use yii\helpers\Url;

return [
    // [
    //     'class' => 'kartik\grid\CheckboxColumn',
    //     'width' => '20px',
    // ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'nomor_antrian',
        'label' => 'No. Antri',
    ],
    [
        'class'     => '\kartik\grid\DataColumn',
        'attribute' => 'nomor_identitas',
        'format'    => 'raw',
        'value' => function($model)
        {
          return substr($model->nomor_identitas, 0, 7) . "<sup>***</sup>";
        }
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'nama',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'jenis_kelamin',
    ],

    [
        'class'     => '\kartik\grid\DataColumn',
        'attribute' => 'is_proses',
        'label'     => 'Status',
        'format'    => 'raw',
        'value' => function($model)
        {
          return $model->formatIsProses($model->is_proses);
        }
    ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'no_telepon',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'nama_ibu_debitur',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'alamat_sesuai_kartu',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'alamat_lain',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'alasan_pengajuan',
    // ],
    // [
    //     'class' => 'kartik\grid\ActionColumn',
    //     'dropdown' => false,
    //     'vAlign'=>'middle',
    //     'urlCreator' => function($action, $model, $key, $index) {
    //             return Url::to([$action,'id'=>$key]);
    //     },
    //     'viewOptions'=>['role'=>'modal-remote','title'=>'View','data-toggle'=>'tooltip'],
    //     'updateOptions'=>['role'=>'modal-remote','title'=>'Update', 'data-toggle'=>'tooltip'],
    //     'deleteOptions'=>['role'=>'modal-remote','title'=>'Delete',
    //                       'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
    //                       'data-request-method'=>'post',
    //                       'data-toggle'=>'tooltip',
    //                       'data-confirm-title'=>'Are you sure?',
    //                       'data-confirm-message'=>'Are you sure want to delete this item'],
    // ],

];

_system/views/site/_columns.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

return [
  // [
  //   'class' => 'kartik\grid\CheckboxColumn',
  //   'width' => '20px',
  // ],
  [
    'class' => 'kartik\grid\SerialColumn',
    'width' => '30px',
  ],
  // [
  // 'class'     => '\kartik\grid\DataColumn',
  // 'attribute' => 'id',
  // ],
  [
    'class'     => '\kartik\grid\DataColumn',
    'attribute' => 'nama_laporan',
  ],
  [
    'class'     => '\kartik\grid\DataColumn',
    'attribute' => 'deskripsi',
    'value' => function ($model) {
      return strlen($model->deskripsi) > 75 ? substr($model->deskripsi, 0, 70) . '...' : $model->deskripsi;
    }
  ],
  [
    'class'     => '\kartik\grid\DataColumn',
    'format'    => 'date',
    'attribute' => 'tanggal_deadline_pelaporan',
  ],
  [
    'class'     => '\kartik\grid\DataColumn',
    'label'     => 'Status Deadline',
    'attribute' => 'deadline',
    'format'    => 'raw',
    'value' => function ($model) {

      return $model->getDeadlineVisual($model->id);
    }
  ],
  // [
  //   'class'     => '\kartik\grid\DataColumn',
  //   'label'     => 'Tanggal Deadline',
  //   'format'    => 'date',
  //   'attribute' => 'deadline',
  //   'value' => function ($model) {
  //     // $hari = $model->deadline ? : '0';
  //     // return $hari . ' Hari';
  //     return $model->getDateDeadline($model->id);
  //   }
  // ],
  // [
  //   'class'     => '\kartik\grid\DataColumn',
  //   'attribute' => 'status',
  //   'format'    => 'raw',
  //   'value' => function ($model) {
  //       return $model->formatStatus($model->status);
  //   }
  // ],
  // [
  //   'class'     => '\kartik\grid\DataColumn',
  //   'label'     => 'Dibuat Oleh',
  //   'attribute' => 'created_user',
  //   'value'     => 'createdUser.username',
  // ],
  // [
  // 'class'     => '\kartik\grid\DataColumn',
  // 'attribute' => 'updated_user',
  // ],
  [
    'class'      => 'kartik\grid\ActionColumn',
    'options' => [
      'style' => 'min-width: 100px',
    ],
    'template'   => '{view}',
    'dropdown'   => false,
    'vAlign'     => 'middle',
    'urlCreator' => function ($action, $model, $key, $index) {
      $url = Url::to([$action, 'id' => $key]);
      return $url;
    },

    'buttons' => [
      'view'   => function ($url, $model) {
        return Html::a('<i class="fa fa-eye"></i> Detail', $url, [
          'data-original-title' => Yii::t('app', 'Lihat'),
          'title'               => Yii::t('app', 'Lihat'),
          'data-toggle'         => 'tooltip',
          'class'               => 'btn btn-primary btn-xs',
          'role'                => 'modal-remote',
        ]);
      },
      'update' => function ($url, $model) {
        return Html::a('<i class="fa fa-pencil"></i>', $url, [
          'data-original-title' => Yii::t('app', 'Perbarui'),
          'title'               => Yii::t('app', 'Perbarui'),
          'data-toggle'         => 'tooltip',
          'class'               => 'btn btn-warning btn-xs',
          'role'                => 'modal-remote',
        ]);
      },
      'delete' => function ($url, $model) {
        return Html::a('<i class="fa fa-trash"></i>', $url, [
          'data-original-title'  => Yii::t('app', 'Hapus'),
          'title'                => Yii::t('app', 'Hapus'),
          'data-toggle'          => 'tooltip',
          'class'                => 'btn btn-danger btn-xs',
          'role'                 => 'modal-remote',
          'data-confirm'         => false,
          'data-method'          => false, // for overide yii data api
          'data-request-method'  => 'post',
          'data-confirm-title'   => Yii::t('app', 'Are you sure?'),
          'data-confirm-message' => Yii::t('app', 'Are you sure want to delete this item'),
        ]);
      }
    ],

    'contentOptions' => [
      'class' => 'td-actions skip-export kv-align-center kv-align-middle',
    ],
  ],

];

_system/views/site/create-badan-usaha.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\master\RecIdebPerorangan */

?>
<div class="rec-ideb-perorangan-create">
    <?= $this->render('_form', [
        'model' => $model,
        'p' => false,
    ]) ?>
</div>

_system/views/site/create-perseorangan.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\master\RecIdebPerorangan */

?>
<div class="rec-ideb-perorangan-create">
    <?= $this->render('_form', [
        'model' => $model,
        'p' => true,
    ]) ?>
</div>

_system/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

_system/views/site/panduan.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = $model->judul;
$this->params['breadcrumbs'][] = $this->title;

$js = <<< JS

$('#btn-ubah-panduan').click(function(){
  $('#v-panduan').hide(function() {
    $('#h-panduan').show();
  });
  $('body').find('#content-panduan').load($(this).attr('value'), function() {
    $('#btn-ubah-panduan').hide(function() {
      $('#btn-submit-panduan').show();
    });
  });
});
$("#btn-submit-panduan").click(function() {
  $('#v-submit').hide(function() {
    $('#h-submit').show();
  });
  $("#form-post").submit();
});

JS;

$this->registerJS($js);

if (!Yii::$app->user->isGuest) {
  $this->params['btn-menu'][] = Html::button('
  <span id="v-panduan">Ubah Panduan</span>
  <i id="h-panduan" class="glyphicon glyphicon-refresh icon-loading" style="display: none;"></i>', [
    'id'    => 'btn-ubah-panduan',
    'title' => 'Ubah Rincian Panduan',
    'class' => 'btn btn-primary',
    'value' => Url::to(['/post/update', 'id' => 1, 'ajax' => 1, 'redirect' => '/site/panduan']),
  ]);
  $this->params['btn-menu'][] = Html::button('
  <span id="v-submit">Simpan</span>
  <i id="h-submit" class="glyphicon glyphicon-refresh icon-loading" style="display: none;"></i>', [
    'id'    => 'btn-submit-panduan',
    'title' => 'Simpan Rincian Panduan',
    'class' => 'btn btn-success',
    'style' => 'display: none;',
  ]);
}

?>

<div id="content-panduan">


  <h1><?= Html::encode($this->title) ?></h1>

  <br>

  <?= $model->konten ?>

  <br><br>

</div>

_system/views/site/slider.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\FileHelper;


$js = <<< JS

$('#btn-unggah').click(function(){
  $('#loading-unggah').show();
  $('#unggah').modal('show').find('#content-unggah').load($(this).attr('value'), function(){
    $('#loading-unggah').hide();
  });
});
$("#submit-unggah").click(function() {
  $("#form-unggah").submit();
  $('#loading-unggah').show(function() {
    $('#content-unggah').hide();
  });
});
$('#btn-hapus').click(function(){
  $('#hapus').modal('show').find('#content-hapus').load($(this).attr('value'));
});

JS;

$this->registerJs($js);

?>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

  <?php

  $dir   = '@webroot/images/galery';
  $files = FileHelper::findFiles(Yii::getAlias($dir));

  ?>

  <!-- Indicators -->
  <ol class="carousel-indicators">

    <?php

    if (!empty($files)) {
      foreach ($files as $i => $file) {
        $path  = pathinfo($file);
        $class = $i == 0 ? " class=\"active\"" : "";

        echo "<li data-target=\"#carousel-example-generic\" data-slide-to=\"{$i}\"{$class}></li>";
      }
    }
    ?>

  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">

    <?php

    $dir = str_replace('@webroot/', Yii::$app->homeUrl, $dir);

    if (!empty($files)) {
      foreach ($files as $i => $file) {
        $path  = pathinfo($file);
        $class = $i == 0 ? " active" : "";
        $src   = $path['basename'];
        $title = $path['filename'];

        echo "<div class=\"item{$class}\"><img src=\"{$dir}/{$src}\" alt=\"{$title}\" style=\"min-height: 350px;\"><div class=\"carousel-caption\">{$title}</div></div>";
      }
    }
    ?>

  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<?php if (!Yii::$app->user->isGuest) {
  ?>

  <div class="btn-group btn-group-justified" style="margin: 12px auto;">
    <div class="btn-group">
      <button id="btn-unggah" type="button" class="btn btn-primary btn-sm" value="<?= Url::to(['/post/slider', 'action' => 'unggah']) ?>"><i class="fa fa-upload"></i> Unggah Slider</button>
    </div>
    <div class="btn-group">
      <button id="btn-hapus" type="button" class="btn btn-default btn-sm" value="<?= Url::to(['/post/slider', 'action' => 'hapus']) ?>"><i class="fa fa-trash"></i> Hapus Slider</button>
    </div>
  </div>

  <div id="unggah" class="modal fade text-left" tabindex="-1" role="dialog" aria-labelledby="Unggah Slider">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Tutup"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Unggah Slider</h4>
        </div>
        <div class="modal-body">

          <div id="content-unggah"></div>

          <div id="loading-unggah" class="progress">
            <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
          </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
          <button id="submit-unggah" type="button" class="btn btn-primary">Simpan</button>
        </div>
      </div>
    </div>
  </div>

  <div id="hapus" class="modal fade text-left" tabindex="-1" role="dialog" aria-labelledby="Hapus Slider">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Tutup"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Hapus Slider <small>Klik gambar untuk hapus</small></h4>
        </div>
        <div class="modal-body">

          <div id="content-hapus"></div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
        </div>
      </div>
    </div>
  </div>

  <?php
} ?>

_system/views/site/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\master\RecIdebPerorangan */
?>
<div class="rec-ideb-perorangan-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>