_system/controllers/ApiController.php
<?php
/**
 * @link http://www.diecoding.com/
 * @author Die Coding (Sugeng Sulistiyawan) <diecoding@gmail.com>
 * @copyright Copyright (c) 2018
 */


namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\RecIdeb;
use app\models\RecLaporan;

use yii\helpers\Json;

class ApiController extends Controller
{
    /**
     * {@inheritdoc}
     */
    // public function behaviors()
    // {
    //     return [
    //         'access' => [
    //             'class' => AccessControl::className(),
    //             'only' => ['logout'],
    //             'rules' => [
    //                 [
    //                     'actions' => ['logout'],
    //                     'allow' => true,
    //                     'roles' => ['@'],
    //                 ],
    //             ],
    //         ],
    //         'verbs' => [
    //             'class' => VerbFilter::className(),
    //             'actions' => [
    //                 'logout' => ['post'],
    //             ],
    //         ],
    //     ];
    // }

    /**
     * {@inheritdoc}
     */
    // public function actions()
    // {
    //     return [
    //         'error' => [
    //             'class' => 'yii\web\ErrorAction',
    //         ],
    //         'captcha' => [
    //             'class' => 'yii\captcha\CaptchaAction',
    //             'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
    //         ],
    //     ];
    // }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionSearchData($q)
    {
        $query = RecLaporan::find()
       ->select('nama_laporan')
       ->where(['LIKE', 'nama_laporan', $q])
       ->groupBy('nama_laporan')
       ->orderBy('nama_laporan');

        $command = $query->createCommand();
        $data = $command->queryAll();
        $out = [];
        foreach ($data as $d) {
            $out[] = ['value' => $d['nama_laporan']];
        }

        return Json::encode($out);
    }
}

_system/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

use app\models\RecIdeb;
use app\models\searchs\RecIdeb as RecIdebSearch;
use app\models\RecLaporan;
use app\models\searchs\RecLaporan as RecLaporanSearch;
use app\models\Posts;

use yii\web\NotFoundHttpException;
use yii\helpers\Html;

class SiteController extends Controller
{
  /**
  * {@inheritdoc}
  */
  public function behaviors()
  {
    return [
      'access' => [
        'class' => AccessControl::className(),
        'only' => ['logout', 'index-secure'],
        'rules' => [
          [
            'actions' => ['logout', 'index-secure'],
            'allow' => true,
            'roles' => ['@'],
          ],
        ],
      ],
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'logout' => ['post'],
        ],
      ],
    ];
  }

  /**
  * {@inheritdoc}
  */
  public function actions()
  {
    return [
      'error' => [
        'class' => 'yii\web\ErrorAction',
      ],
      'captcha' => [
        'class' => 'yii\captcha\CaptchaAction',
        'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
      ],
    ];
  }

  /*
   * Lists all RecLaporan models.
   * @return mixed
   */
  public function actionIndex()
  {
    $searchModel  = new RecLaporanSearch();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
    $dataProvider->pagination->pageSize = 3;

    return $this->render('index', [
      'searchModel'  => $searchModel,
      'dataProvider' => $dataProvider,
    ]);
  }

  /*
   * Displays a single RecLaporan model.
   * @param integer $id
   * @return mixed
   */
  public function actionView($id)
  {
    $request = Yii::$app->request;

    if ($request->isAjax) {
      Yii::$app->response->format = Response::FORMAT_JSON;
      return [
        'title'   => "RecLaporan #{$id}",
        'content' => $this->renderAjax('view', [
          'model' => $this->findModel($id),
        ]),
        'footer'  => '<div class="col-xs-12">'.
          Html::button(Yii::t('app', 'Tutup'), [
            'class'        => 'btn btn-default',
            'data-dismiss' => 'modal',
          ]
          ) .
        '</div>'
      ];
    }

    return $this->goHome();
  }

  /**
  * Displays homepage.
  *
  * @return string
  */
  public function actionIndexSecure()
  {
    $searchModel                        = new RecIdebSearch();
    $dataProvider                       = $searchModel->search(Yii::$app->request->queryParams);
    $dataProvider->pagination->pageSize = 10;

    return $this->render('index-secure', [
      'searchModel' => $searchModel,
      'dataProvider' => $dataProvider,
    ]);
  }


  /**
  * Creates a new RecIdeb model.
  * For ajax request will return json object
  * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
  * @return mixed
  */
  public function actionCreate($action = 'perseorangan')
  {
    $request = Yii::$app->request;
    $model   = new RecIdeb();

    if ($request->isAjax) {

      /*
      *  Process for ajax request
      */
      Yii::$app->response->format = Response::FORMAT_JSON;
      if ($request->isGet) {
        return [
          'title'   => Yii::t('app', 'Formulir Permohonan IDEB ' . strtoupper(str_replace("-", " ", $action))),
          'content' => $this->renderAjax('create-' . strtolower($action), [
            'model' => $model,
          ]),
          'footer'  => '<div class="col-md-12">'.
          Html::button(Yii::t('app', 'Tutup'), [
            'class'        => 'btn btn-default',
            'data-dismiss' => 'modal',
          ]
          ) .
          Html::button(Yii::t('app', 'Simpan'), [
            'class' => 'btn btn-primary',
            'type'  => 'submit',
          ]
          ) .
          '</div>'
        ];
      }

      if ($model->load($request->post())) {

        if (($data = $model->setCreate(strtoupper($action))) && $model->save()) {
          return [
            'forceReload' => '#crud-datatable-pjax',
            'title'       => Yii::t('app', 'Formulir Permohonan IDEB ' . strtoupper(str_replace("-", " ", $action))),
            'content'     => '<span class="text-success">'.Yii::t('app', 'Data berhasil disimpan').'</span>',
            'footer'      => '<div class="col-md-12">'.
            Html::button(Yii::t('app', 'Tutup'), [
              'class'        => 'btn btn-default',
              'data-dismiss' => 'modal',
            ]
            ) .
            Html::a(Yii::t('app', 'Isi Formulir Lagi'),
            ['create', 'action' => $action],
            [
              'class' => 'btn btn-primary',
              'role'  => 'modal-remote',
            ]
            ) .
            '</div>'
          ];
        } else {
          return [
            'title'   => Yii::t('app', 'Formulir Permohonan IDEB ' . strtoupper(str_replace("-", " ", $action))),
            'content' => $this->renderAjax('create-' . strtolower($action), [
              'model' => $model,
            ]),
            'footer'  => '<div class="col-md-12">'.
            Html::button(Yii::t('app', 'Tutup'), [
              'class'        => 'btn btn-default',
              'data-dismiss' => 'modal',
            ]
            ) .
            Html::button(Yii::t('app', 'Simpan'), [
              'class' => 'btn btn-primary',
              'type'  => 'submit',
            ]
            ) .
            '</div>'

          ];
        }
      }
    }

    /*
     *  Process for non-ajax request
     */
    if ($model->load($request->post())) {

      // echo "<pre>";print_r($model->setCreate());exit;

      if (($data = $model->setCreate(strtoupper($action))) && $model->save()) {
        Yii::$app->session->setFlash('success', Yii::t('app', 'Data berhasil disimpan'));
      }
    }

    return $this->render('create-' . strtolower($action), [
      'model' => $model,
    ]);
  }

  /**
  * Login action.
  *
  * @return Response|string
  */
  public function actionLogin()
  {
    if (!Yii::$app->user->isGuest) {
      return $this->goHome();
    }

    $model = new LoginForm();
    if ($model->load(Yii::$app->request->post()) && $model->login()) {
      return $this->goBack();
    }

    $model->password = '';
    return $this->render('login', [
      'model' => $model,
    ]);
  }

  /**
  * Logout action.
  *
  * @return Response
  */
  public function actionLogout()
  {
    Yii::$app->user->logout();

    return $this->goHome();
  }

  /**
  * Displays contact page.
  *
  * @return Response|string
  */
  // public function actionContact()
  // {
  //   $model = new ContactForm();
  //   if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
  //     Yii::$app->session->setFlash('contactFormSubmitted');
  //
  //     return $this->refresh();
  //   }
  //   return $this->render('contact', [
  //     'model' => $model,
  //   ]);
  // }

  /**
  * Displays panduan page.
  *
  * @return string
  */
  public function actionPanduan()
  {
    $model = Posts::findOne(1);

    return $this->render('panduan', [
      'model' => $model
    ]);
  }


  /*
   * Finds the RecLaporan model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param integer $id
   * @return RecLaporan the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id)
  {

    if (($model = RecLaporan::findOne($id)) !== null) {
      return $model;
    }

    throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
  }
}

_system/controllers/UserController.php
<?php
/**
 *
 *
 * @link      http://www.diecoding.com/
 * @author    Die Coding (Sugeng Sulistiyawan) <diecoding@gmail.com>
 * @copyright Copyright (c) 2018
 */


namespace app\controllers;

use Yii;
use app\models\User;
use app\models\searchs\User as UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\SignupForm;

/**
 *
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{

    /**
     *
     *
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
        'access' => [
        'class' => AccessControl::className(),
        'rules' => [
          [
            'actions' => ['index', 'signup'],
            'allow'   => true,
            'roles'   => ['@'],
          ],
        ],
        ],
        'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'delete' => ['POST'],
        ],
        ],
        ];
    }

    /**
     *
     * Lists all User models.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render(
            'index',
            [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            ]
        );
    }

    /**
     *
     * Displays a single User model.
     *
     * @param  integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render(
            'view',
            [
            'model' => $this->findModel($id),
            ]
        );
    }

    /**
     *
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render(
                'create',
                [
                'model' => $model,
                ]
            );
        }
    }

    /**
     *
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param  integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render(
                'update',
                [
                'model' => $model,
                ]
            );
        }
    }

    /**
     *
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param  integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     *
     * Signs user up.
     *
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                return $this->redirect(['/user']);
            }
        }

        return $this->render(
            'signup',
            [
            'model' => $model,
            ]
        );
    }

    /**
     *
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param  integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

_system/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use app\assets\AppAsset;

use kartik\widgets\Typeahead;
use yii\helpers\Url;
use yii\web\JsExpression;
use yii\widgets\ActiveForm;

AppAsset::register($this);

$css = <<< CSS
.icon-loading{-animation:s .7s infinite linear;-ms-animation:s .7s infinite linear;-webkit-animation:sw .7s infinite linear;-moz-animation:sm .7s infinite linear}@keyframes s{from{transform:scale(1)rotate(0deg)}to{transform:scale(1)rotate(360deg)}}@-webkit-keyframes sw{from{-webkit-transform:rotate(0deg)}to{-webkit-transform:rotate(360deg)}}@-moz-keyframes sm{from{-moz-transform:rotate(0deg)}to{-moz-transform: rotate(360deg)}}
CSS;

$this->registerCss($css);

$js = <<< JS

$('#inp-submit').click(function() {
  $('#form-search').submit();
  $('#h-search').show();
  $('#v-search').hide();
});

// $('.btn-fullscreen').click(function() {
//   var docElm = document.documentElement;
//   if (docElm.requestFullscreen) {
//     docElm.requestFullscreen();
//   } else if (docElm.mozRequestFullScreen) {
//     docElm.mozRequestFullScreen();
//   } else if (docElm.webkitRequestFullScreen) {
//     docElm.webkitRequestFullScreen();
//   } else if (docElm.msRequestFullscreen) {
//     docElm.msRequestFullscreen();
//   }
// });

JS;

$this->registerJs($js);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?php echo Yii::$app->language ?>">
<head>
  <meta charset="<?php echo Yii::$app->charset ?>">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?php echo Html::csrfMetaTags() ?>
  <title><?php echo isset($this->title) ? Html::encode($this->title) : Yii::$app->name ?></title>
  <?php $this->head() ?>
</head>
<body>
  <?php $this->beginBody() ?>

  <div class="visible-alert" style="margin: 40px 28px;">
    <div class="alert alert-danger">
      Hanya dapat digunakan pada layar berukuran lebar minimum 992px
    </div>
  </div>

  <div class="hide-alert">

    <div class="wrap">
      <nav id="w3" class="navbar-inverse navbar-fixed-top navbar">
        <div class="container">
          <!-- <div class="navbar-header"> -->
          <!-- <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#w3-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button> -->
        <div class="row">

          <div class="col-sm-3">
            <a class="logo-left" href="<?php echo Yii::$app->homeUrl ?>">
              <img src="<?php echo Yii::$app->homeUrl ?>images/header.png" alt="">
            </a>
          </div>

          <div class="col-sm-6 text-center logo-center">
            <h1><strong>SLIK SOLO</strong></h1>
            <h5>SISTEM LAYANAN INFORMASI KEUANGAN SOLO</h5>
          </div>

          <div class="col-sm-3">
            <a class="logo-right" href="<?php echo Yii::$app->homeUrl ?>">
              <img src="<?php echo Yii::$app->homeUrl ?>images/header-way.png" alt="">
            </a>
          </div>

        </div>

        <!-- </div> -->
        <!-- <div id="w3-collapse" class="collapse navbar-collapse"></div> -->
      </div>
    </nav>

    <div class="container-fluid">

      <div class="row" style="margin-bottom: 20px;">

        <div class="col-md-4">
          <?php

          $form = ActiveForm::begin(
            [
              'id'     => 'form-search',
              'action' => Yii::$app->user->isGuest ? ['/site'] : ['/laporan'],
              'method' => 'get',
            ]
          );

          ?>

          <div class="form-group">
            <div class="input-group">

              <?php
              /**
              * Prefetches some data then relies on remote requests (ajax) via Controller action
              * for suggestions when prefetched data is insufficient.
              * The json encoded prefetch source is:
              * [{value:"Andorra"}, {value:"United Arab Emirates"}, {value:"Afghanistan"},
              *  {value:"Antigua and Barbuda"}, {value:"Anguilla"}, {value:"Albania"}]
              */
              echo Typeahead::widget(
                [
                  'id' => 'inp-search',
                  'name' => 'RecLaporan[nama_laporan]',
                  'options' => [
                    'placeholder' => 'Cari data...',
                    'required'    => true,
                  ],
                  'pluginOptions' => [
                    'highlight' => true,
                  ],
                  'dataset' => [
                    [
                      'datumTokenizer' => "Bloodhound.tokenizers.obj.whitespace('value')",
                      'display' => 'value',
                      'prefetch' => $baseUrl . '/data/search.json',
                      'templates' => [
                        'notFound' => '<div class="tt-suggestion" style="color: #a94442;">Tidak ada data yang ditemukan.</div>',
                      ],
                      'remote' => [
                        'url' => Url::to(['/api/search-data']) . '?q=%QUERY',
                        'wildcard' => '%QUERY'
                      ]
                    ]
                  ]
                ]
              );

              ?>
              <span id="inp-submit" class="input-group-addon btn">
                <i id="v-search" class="glyphicon glyphicon-search"></i>
                <i id="h-search" class="glyphicon glyphicon-refresh icon-loading" style="display: none;"></i>
              </span>

            </div>
          </div>

          <?php ActiveForm::end() ?>
        </div>

        <div class="col-md-8">

          <div class="pull-right">

            <div class="btn-group">

              <?php echo Html::a('Beranda', ['/'], ['class' => 'btn btn-default']) ?>
              <?php echo Html::a('Panduan', ['/site/panduan'], ['class' => 'btn btn-default']) ?>

              <?php
              if (isset($this->params['btn-menu'])) {
                  foreach ($this->params['btn-menu'] as $btn) {
                      echo "{$btn} ";
                  }
              }
              ?>

              <?php if (!Yii::$app->user->isGuest) {
                  ?>

                <!-- Single button -->
                <div class="btn-group">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Admin <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" style="right: 0; left: auto;">
                    <li><?php echo Html::a('Data Laporan', ['/laporan']) ?></li>
                    <li><?php echo Html::a('Data IDEB Perseorangan', ['/ideb', 'action' => 'perseorangan']) ?></li>
                    <li><?php echo Html::a('Data IDEB Badan Usaha', ['/ideb', 'action' => 'badan-usaha']) ?></li>
                    <li><?php echo Html::a('Data Admin', ['/user']) ?></li>
                    <!-- <li><?php echo Html::a('Tambah Admin', ['/user/signup']) ?></li> -->
                    <!-- <li role="separator" class="divider"></li>
                    <li><?php echo Html::a('Index 1', ['/site/index']) ?></li>
                    <li><?php echo Html::a('Index 2', ['/site/index-secure']) ?></li> -->
                    <li role="separator" class="divider"></li>
                    <li><?php echo Html::a('Logout (<strong>'.Yii::$app->user->identity->username.'</strong>)', ['/site/logout'], ['data-method' => 'post']) ?></li>
                  </ul>
                </div>

                <?php
              } else {
                  ?>

                  <?php echo Html::a('Login', ['/site/login'], ['class' => 'btn btn-default']) ?>

              <?php
              } ?>
            </div>
          </div>
        </div>

      </div>

      <?php // echo Alert::widget()?>

      <?php echo $content ?>

    </div>
  </div>

  <footer class="footer">
    <div class="container-fluid">
      <p class="text-center">
        <?php echo getenv('APP_FOOTER') ?>
      </p>
    </div>
  </footer>

</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>